# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import data_pb2 as data__pb2


class DoFormatStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_Weather = channel.unary_unary(
                '/com.learn.demo.DoFormat/get_Weather',
                request_serializer=data__pb2.IP.SerializeToString,
                response_deserializer=data__pb2.DataList.FromString,
                )


class DoFormatServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_Weather(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DoFormatServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_Weather': grpc.unary_unary_rpc_method_handler(
                    servicer.get_Weather,
                    request_deserializer=data__pb2.IP.FromString,
                    response_serializer=data__pb2.DataList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.learn.demo.DoFormat', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DoFormat(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_Weather(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.learn.demo.DoFormat/get_Weather',
            data__pb2.IP.SerializeToString,
            data__pb2.DataList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
